# Generated by Django 3.1.4 on 2021-01-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techsupportapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answerDate',
        ),
        migrations.RemoveField(
            model_name='question',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='questionDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания заявки'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionName',
            field=models.CharField(max_length=100, null=True, verbose_name='Название заявки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Наименование отдела'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=80, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Наименование должности'),
        ),
        migrations.AlterField(
            model_name='question',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsupportapp.division'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(null=True, verbose_name='Содержание заявки'),
        ),
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='Статус заявки')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsupportapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ по заявке')),
                ('answerDate', models.DateField(verbose_name='Дата ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsupportapp.question')),
            ],
        ),
    ]
